openapi: 3.0.0
info:
  title: Alta Final Project API
  description: API for alta final Project
  version: 1.0.0
  contact:
    email: hanifbg48@gmail.com
servers:
  - url: 'http://hanifbg.com'

paths:
  /login:
    post:
      tags:
      - login
      summary: Login users or admin
      requestBody:
        description: Optional description in *markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/LoginInfo'
            example:
              email: main@maiil.com
              password: password   
      responses:
        '200':
          description: Login Token
          content:
            application/jwt:
              schema:
                type: string
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

components:
  requestBodies:
    LoginInfo:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/LoginInfo" 
      description: User object that need to Login
      required: true

  schemas:
    LoginInfo:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string